### ISSUE TITLE
Raspbian Support?

### ISSUE THREAD

**Issue by code-monki** [ipv6rslimited/cloudseeder#1]
Greetings,

This is more of a question about whether or not cloudseeder supports Raspbian because I couldn't find anywhere on your site to ask this.

**Comment by ipv6rs** [comment]
Hi code-monki,

Right now you need gnome-terminal to use Cloud Seeder. This is the only dependency that may prevent it from running on Raspbian. You can install Gnome on Raspbian, but this is a bit heavy just to use this application.

We are working on removing external terminal dependency and a newer version will work on Raspbian.

We apologize for any inconvenience this may cause!

**Comment by ipv6rs** [comment]
I will leave this open and update when Raspbian support arrives!

**Comment by ipv6rs** [comment]
This should remove any blockers from raspbian as it works with lxterminal and xterm as well (for shell access)!
All other operations do not have an external dependency and you can technically simply access the shell with `podman exec -it <name of container> /bin/bash`!

Thank you for your patience!

**Comment by ipv6rs** [comment]
https://github.com/ipv6rslimited/cloudseeder/releases/tag/v1.1.0
