### ISSUE TITLE
Raspbian Testing: App not appearing

### ISSUE THREAD

**Issue by mark-zarandi** [ipv6rslimited/cloudseeder#4]
Cloud seeder isn't quite launching from the desktop like you described in your instructions.  It looks like a small tile comes into the taskbar but it immediately disappears. I installed xterm and podman.  Drop me a line and I'll help contribute to testing.

**Comment by ipv6rs** [comment]
Hi @mark-zarandi,

Thank you for your patience and thank you for the feedback. When you launch the application, if I understand correctly, it's not even opening.

Thank you for your generosity in resolving this issue.

Would you perhaps be open to launching the software from the terminal and let us know if there are any text outputs?

Thank you in advance!

**Comment by mark-zarandi** [comment]
pleasure to help.  so i tried ./cloudseeder while in the bin directory with and without sudo.  Without, it reads "Exec format error".  When I used sudo it says "Syntax error ')' expected".

**Comment by ipv6rs** [comment]
This is curious.

Did you download the ARM64 or AMD64 version?

**Comment by mark-zarandi** [comment]
Yes, arm 64. It's an RPI 3b+, fresh raspbian install.  I saw there were some missing updates last night so i installed those and tried again without any luck.  I tried to execute it both in XTerm and LXterm.

**Comment by ipv6rs** [comment]
I looked at this: https://stackoverflow.com/questions/77457714/compiling-go-fyne-on-raspberry-pi

And it appears that to compile a fyne app to run on raspbian, certain dev library headers/files are required.

Thus, to run these it looks like you'll need the following:
```
sudo apt-get install libgles2-mesa libglfw3 libxxf86vm1 libxrandr2 libxinerama1 libxcursor1 libxi6 libx11-xcb1 libxkbcommon0 libwayland-client0 libwayland-egl1
```
I'm not sure if this is going to be, however, conflicting with your system's current environment so please don't tread this direction unless you're certain it won't!

In the meantime we will try to get a hold of a Raspberry PI!

**Comment by ipv6rs** [comment]
We're looking further and it appears there are 32 bit versions of the Raspberry Pi 3b+

https://forums.raspberrypi.com/viewtopic.php?t=213405

**Comment by ipv6rs** [comment]
We added a 32bit build of the Linux Cloud Seeder

https://ipv6.rs/cloudseeder/

Please let us know if this addresses the issue! Thank you again for your patience and understanding.

**Comment by mark-zarandi** [comment]
Works fine now, thanks.  I got to sit down and register for an account then I'll follow-up.
